### PR TITLE
Some improvements

### PR DESCRIPTION
**Pull request by martinRenou**
- Fix triangles indices
- Add Suzanne
- Use voila-material
- Update thumbnail

### CODE REVIEW

**Comment by martinRenou** [comment]
@jtpio

**Comment by martinRenou** [comment]
Note: I had to remove the wireframe feature as it is not supported by `plot_trisurf`, but `plot_trisurf` is the right way to go otherwise there are some glitches (triangle indices errors, `plot_mesh` is not made for that).

with `plot_mesh`:
bad

with `plot_trisurf`:
good

**Comment by jtpio** [comment]
How does the thumbnail render on the page? (when resized)

**Comment by martinRenou** [comment]
Looks good! Already deployed on the gallery as you can see:
looksgood

**Review by jtpio — APPROVED** [review]
Thanks!

**Pull request merged**
